---
abstract: 'Parsing string like command line'
author:
  - 'Songmu <y.songmu@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.14.1, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-CommandLine
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Parse::CommandLine:
    file: lib/Parse/CommandLine.pm
    version: 0.01
requires:
  parent: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/Songmu/p5-Parse-CommandLine/issues
  homepage: https://github.com/Songmu/p5-Parse-CommandLine
  repository: git://github.com/Songmu/p5-Parse-CommandLine.git
version: 0.01
x_authority: cpan:SONGMU
